MySite/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MySite.Models;
using System;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;

namespace MySite.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {

        private IPost repository;
        public const int ImageMinimumBytes = 512;
        private readonly UserManager<User> _userManager;
        private readonly IProfile _profile;
        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public AdminController(IPost repository, UserManager<User> userManager, IProfile profile)
        {
            _profile = profile;
            _userManager = userManager;
            this.repository = repository;

        }
        private int CountNewPosts { get { return repository.Posts.Where(p => p.Allow == 0).Count(); } }

        public ViewResult Index() => View(repository.Posts.Where(p => p.Allow == 1));

        public ViewResult Edit(int postID) =>
            View(repository.Posts.FirstOrDefault(p => p.PostID == postID));

        public static bool IsImage(IFormFile postedFile)
        {

            if (postedFile.ContentType.ToLower() != "image/jpg" &&
                        postedFile.ContentType.ToLower() != "image/jpeg" &&
                        postedFile.ContentType.ToLower() != "image/pjpeg" &&
                        postedFile.ContentType.ToLower() != "image/gif" &&
                        postedFile.ContentType.ToLower() != "image/x-png" &&
                        postedFile.ContentType.ToLower() != "image/png")
            {
                return false;
            }

            if (Path.GetExtension(postedFile.FileName).ToLower() != ".jpg"
                && Path.GetExtension(postedFile.FileName).ToLower() != ".png"
                && Path.GetExtension(postedFile.FileName).ToLower() != ".gif"
                && Path.GetExtension(postedFile.FileName).ToLower() != ".jpeg")
            {
                return false;
            }
            try
            {
                if (!postedFile.OpenReadStream().CanRead)
                {
                    return false;
                }

                if (postedFile.Length < ImageMinimumBytes)
                {
                    return false;
                }

                byte[] buffer = new byte[512];
                postedFile.OpenReadStream().Read(buffer, 0, 512);
                string content = System.Text.Encoding.UTF8.GetString(buffer);
                if (Regex.IsMatch(content, @"<script|<html|<head|<title|<body|<pre|<table|<a\s+href|<img|<plaintext|<cross\-domain\-policy",
                    RegexOptions.IgnoreCase | RegexOptions.CultureInvariant | RegexOptions.Multiline))
                {
                    return false;
                }
            }
            catch (Exception)
            {
                return false;
            }

            return true;
        }
        [HttpPost]
        public IActionResult DeleteAvatar(int profileID)
        {

            Profile profile = _profile.Profiles.FirstOrDefault(p => p.ProfileID == profileID);
            if (profile != null)
            {
                profile.ImageData = null;
                profile.ImageMimeType = null;
                _profile.SaveProfile(profile);
            }
            return View("Edit", "Profile");
        }
        [HttpPost]
        public IActionResult DeleteImage(int postID)
        {

            Post post = repository.Posts.FirstOrDefault(p => p.PostID == postID);
            if (post != null)
            {
                post.ImageData = null;
                post.ImageMimeType = null;
                repository.SaveProduct(post);
            }
            return View("Edit", postID);
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Edit(Post post, IFormFile image = null)
        {
            if (ModelState.IsValid)
            {

                if (image != null)
                {


                    if (IsImage(image))
                    {
                        post.ImageMimeType = image.ContentType;
                        post.ImageData = new byte[image.Length];
                        image.OpenReadStream().Read(post.ImageData, 0, (int)image.Length);

                    }
                    else
                    {
                        TempData["error"] = $"It's not image";
                        return View(post);
                    }

                }
                var user = await GetCurrentUserAsync();
                var profile = _profile.Profiles.FirstOrDefault(p => p.UserID == user.Id);
                post.UserID = user.Id;
                post.DateTime = DateTime.Now;
                post.ProfileID = profile.ProfileID;
                post.Author = profile.FirstName == null ? user.Email.Split("@")[0] : profile.FirstName;
                repository.SaveProduct(post);
                if (User.IsInRole("admin"))
                {
                    TempData["message"] = $"{post.Title} has been saved";
                    post.Allow = 1;
                }
                else
                {
                    TempData["message"] = "Your post is saved and will be reviewed";
                    post.Allow = 0;
                }
                if (User.IsInRole("admin"))
                    return RedirectToAction("Index");
                else
                    return RedirectToAction("Index", "Home");
            }
            else
            {
                if (User.IsInRole("admin"))
                    return View(post);
                else
                    return RedirectToAction("AddPost", "Home", post);
            }
        }

        public IActionResult Menu() => View();
        public IActionResult NewPosts() => View(repository.Posts.Where(p => p.Allow == 0));
        public ViewResult Create() => View("Edit", new Post());

        [HttpPost]
        public IActionResult CancelPost(int postID)
        {
            Post post = repository.Posts.FirstOrDefault(p => p.PostID == postID);
            if (post != null)
            {
                post.Allow = 3;
                repository.SaveProduct(post);
            }
            return View("NewPosts");
        }
        [HttpPost]
        public IActionResult AcceptPost(int postID)
        {
            Post post = repository.Posts.FirstOrDefault(p => p.PostID == postID);
            if (post != null)
            {
                post.Allow = 1;
                repository.SaveProduct(post);
            }
            return View("NewPosts");
        }



        [HttpPost]
        public IActionResult Delete(int postID)
        {
            Post deletedPost = repository.DeletePost(postID);
            if (deletedPost != null)
                TempData["message"] = $"{ deletedPost.Title} was deleted";
            else
                TempData["message"] = $"{ deletedPost.Title} was'nt deleted";

            return RedirectToAction("Index");
        }
    }
}

MySite/Controllers/RolesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using MySite.Models;
using MySite.Models.ViewModels;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;

namespace MySite.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("Index", "Users");
            }

            return NotFound();
        }
    }
}

MySite/Views/Shared/RegisterPartial.cshtml
@{ 
    Layout = null;
}

MySite/Views/Shared/ShowBlocksPartial.cshtml
@{ Layout = null;}
@model PostViewModel
<div class="row">
    <div class="col-lg-11 col-md-10 mx-auto">
        @foreach (var item in Model.Posts)
        {
            <div class="card mb-5 border-0" style="back">
                <a asp-controller="Home" asp-action="Post" asp-route-postID="@item.PostID" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()" class="card-link">
                    @if (item.ImageData != null && item.ImageMimeType != null)
                    {
                        <img class="card-img-top hoverImage" src="@Url.Action("GetImage", "Home" ,
                 new {item.PostID })" width="720" height="170" alt="Dowload image">
                    }
                    else
                    {
                        <img class="card-img-top hoverImage" src="https://picsum.photos/723/170/?random" alt="Card image cap">
                    }
                </a>
                <div class="card-body">
                    <a asp-controller="Home" asp-action="Post" asp-route-postID="@item.PostID" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()" class="card-link">
                        <h5 class="card-title">@item.Title</h5>
                    </a>
                    <p class="card-text">@Html.Raw(item.Description)</p>
                    <p class="post-meta float-right">
                        <small class="text-muted">
                            Posted by 
                            <a asp-action="Index" asp-controller="Profile" asp-route-profileID="@item.ProfileID">@item.Author</a>
                        </small>
                    </p>
                    @{
                        int last = (int)DateTime.Now.Subtract(item.DateTime).TotalMinutes;
                        string lastText = "mins";

                        //var last = int.Parse(time);

                        if (last >= 60 && lastText == "mins")
                        {
                            last = last / 60;
                            lastText = "hour";
                        }
                        if (last >= 24 && lastText == "hour")
                        {
                            last = last / 24;
                            lastText = "day";
                        }
                        if (last >= 30 && lastText == "day")
                        {
                            last = last / 30;
                            lastText = "month";
                        }
                        if (last >= 12 && lastText == "month")
                        {
                            last = last / 12;
                            lastText = "year";
                        }

                    }
                    <p class="card-text"><small class="text-muted">Last updated @last @lastText ago</small></p>
                </div>
            </div>
            <hr>
        }

    </div>
</div>
@* Page *@
<div page-model="@Model.PagingInfo" page-url-title="@Model.CurrentSearchTitle" page-action="Index" page-classes-enabled="true"
     page-class="btn" page-class-normal="btn-default"
     page-class-selected="btn-primary" page-url-category="@Model.CurrentCategory"
     class="btn-group pull-right">
</div>

<style>


    .hoverImage:hover {
        -moz-box-shadow: 0 0 12px #c2a3a3;
        -webkit-box-shadow: 0 0 12px #c2a3a3;
        box-shadow: 0 0 12px #c2a3a3;
    }
</style>

MySite/Views/Shared/ShowBreadcrumb.cshtml
@model BreadcrumbViewModel

<nav aria-label="breadcrumb" style="margin-top:-50px">
    <small>
        <ol class="breadcrumb" style="background-color:white">
            <li class="breadcrumb-item" href="#"><a asp-controller="Home" asp-action="Index" class="alert-link">Home</a></li>
            @if (!Model.Active)
            {
                <li class="breadcrumb-item" aria-current="page"><a class="alert-link" asp-controller="Home" asp-action="Index" asp-route-category="@Model.Category">@Model.Category</a></li>
            }
            else
            {
                <li class="breadcrumb-item active" aria-current="page"><a class="alert-link" href="#" id="activeImage">@Model.Category</a></li>

            }
            @if (Model.CurrentName != null)
            {
                <li class="breadcrumb-item active alert-link" aria-current="page"><a id="active" href="#">@Model.CurrentName</a></li>
            }
        </ol>
    </small>
</nav>
<style>
    .breadcrumb a:hover, a:focus {
        text-decoration: none;
        color: #0085A1;
    }

    #active {
        color: #6C757D;
    }

    #active:hover {
        color: #424B53;
    }
</style>

MySite/Views/Shared/ShowEditFormForPost.cshtml
@model Post

<div class="panel-body">

    @using (Html.BeginForm("Edit", "Admin",
FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(p => p.PostID)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {

                    case "UserID":
                    case "PostID":
                    case "ProfileID":
                    case "ImageData":
                    case "ImageMimeType":
                    case "DateTime":
                    case "Allow":
                    case "Author":
                        break;
                    default:
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @if (property.PropertyName == "Description" || property.PropertyName == "Text")
                            {
                                @Html.TextArea(property.PropertyName, null,
                                    new { @class = "form-control", rows = 5})
                            }
                            else
                            {

                                @Html.TextBox(property.PropertyName, null,
                                    new { @class = "form-control" })
                            }
                            <p style="color:red;font-size:14px"><b>@Html.ValidationMessage(property.PropertyName) </b></p>
                        </div>
                        break;
                }
            }
            <div class="form-group">

                <div style="position:relative;">
                    <label>Header Image</label>
                    <a class='btn' href='javascript:;'>
                        Select File...
                        <input type="file" name="Image" size="40"
                               style="position:absolute;z-index:2;top:0;
                                 left:0;filter: alpha(opacity=0); opacity:0;
                                 background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (TempData["error"] != null)
                {
                    <div class="alert alert-danger">@TempData["error"]</div>
                }
                else
                {
                    @if (Model.ImageData == null)
                    {
                        <div class="form-control-static">No Image</div>
                    }
                    else
                    {

                        <img class="img-thumbnail" width="150" height="150"
                             src="@Url.Action("GetImage", "Home",new { Model.PostID })" />
                        @*@using (Html.BeginForm("DeleteImage", "Admin", FormMethod.Post))
                        {
                            @Html.HiddenFor(p => p.PostID)
                            <button type="submit" class="btn btn-danger btn-sm">
                                Delete
                            </button>
                        }*@
                    }

                }

            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            <a asp-action="Index" asp-controller="Admin" class="btn btn-danger">Cancel</a>
        </div>
    }
</div>

MySite/Views/Shared/ShowProfileNav.cshtml
@if (Model)
{
    <nav class="nav flex-column" style="margin-right:100px">
        <a class="nav-link active" asp-action="Index" asp-controller="Profile">Information</a>
        <a class="nav-link" asp-controller="Profile" asp-action="Management">Management</a>
        <a class="nav-link" asp-controller="Profile" asp-action="Edit">Edit</a>
    </nav>
    <style>
        @@media only screen and (max-width: 500px) {
            .flex-column {
                flex-direction: row !important;
                margin: auto !important;
            }
        }
    </style>
}

MySite/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Admin Panel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link asp-href-include="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" asp-href-include="~/admin/css/styles.css" />

    <link rel="icon" type="image/png" asp-href-include="~/favicon/fav.png" />

    <script asp-src-include="~/admin/ckeditor/ckeditor.js"></script>
    <script asp-src-include="~/vendor/jquery/jquery.min.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-131372400-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-131372400-1');
    </script>
    <!-- Normalize-->
    <link rel="stylesheet" asp-href-include="~/normalize.css/normalize.css" />
    <style>

        #logo {
            color: #e1c9c9 !important;
        }

            #logo:hover {
                color: #efdbdb !important;
            }

        .normalButton {
            height: 30px !important;
            width: 32px !important;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="container">
            <nav class="navbar navbar-light bg-light">
                <a class="navbar-brand" id="logo" href="#">
                    <img src="https://cdn4.iconfinder.com/data/icons/standard-free-icons/100/Setting-512.png" width="30" height="30" class="d-inline-block align-top" alt="">
                    Admin Panel
                </a>
                <div class="form-inline my-2 my-lg-0">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:#ffffff">
                        My Account
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">My Profile</a>
                        <a class="dropdown-item" asp-action="Index" asp-controller="Admin">Admin Panel</a>
                        <a class="dropdown-item" asp-action="Index" asp-controller="Home" style="color:#D92420">Exit</a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <div class="page-content">
        <div class="row">
            <div class="col-md-2">
                <div class="sidebar content-box" style="display: block;">
                    <ul class="nav">
                        <!-- Main menu -->
                        <li><a asp-action="NewPosts" asp-controller="Admin" id="newposts"><i class="fab fa-github-alt"></i> New Posts <span id="newPostsText" style="color:#7A7A7A">[<showNotificationCount></showNotificationCount>]</span></a></li>

                        <li><a asp-action="Index" asp-controller="Admin" id="posts"><i class="fas fa-database"></i> Posts</a></li>
                        <li><a asp-action="Index" asp-controller="Users" id="users"><i class="fas fa-users"></i> Users</a></li>
                        <li><a asp-action="Index" asp-controller="Roles" id="roles"><i class="fas fa-pencil-ruler"></i>Roles </a></li>
                    </ul>
                </div>
            </div>
            @RenderBody()
        </div>
    </div>

    <script asp-src-include="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script asp-src-include="~/bootstrap-confirmation2/dist/*.min.js"></script>
</body>
</html>
<script>
    function changeurl(controller, action) {
        var new_url = "hhttps://localhost:44383/" + controller + "/" + action;
        window.history.pushState("data", "Title", new_url);
        $(document).ready(function () {

            $("#newposts").on("click", function (a) {
                alert("Hi");
                a.preventDefault();
                changeurl("Admin", "NewPosts");
                $("#content").load("/Admin/NewPosts");
            });
            $("#posts").on("click", function (b) {
                b.preventDefault();
                changeurl("Admin", "Index");
                $("#content").load("/Admin/GetAjaxView", { viewname: "Index" });
            });

            $("#users").on("click", function (c) {
                c.preventDefault();
                changeurl("Users", "Index");
                $("#content").load("/Users/Index");
            });
            $("#roles").on("click", function (d) {
                d.preventDefault();
                changeurl("Roles", "Index");
                $("#content").load("/Roles/Index");
            });
        });
</script>

MySite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" />
    <title>MarcBlog</title>
    @RenderSection("Style", false)
    <!-- Bootstrap core CSS -->
    <link asp-href-include="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!--Favicon-->
    <link rel="icon" type="image/png" asp-href-include="~/favicon/fav.png" />
    <!-- Custom fonts for this template -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!-- Normalize-->
    <link rel="stylesheet" asp-href-include="~/normalize.css/normalize.min.css" />

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-131372400-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-131372400-1');
    </script>

    <link asp-href-include="~/css/my-blog.min.css" rel="stylesheet">


    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body>
    <style>
    </style>
    <!-- Navigation -->
    @await Component.InvokeAsync("UserMenu")

    @RenderBody()
    <hr>
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; MarcBlog 2018</p>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JavaScript -->
    <script asp-src-include="~/vendor/jquery/jquery.min.js"></script>
    <script asp-src-include="~/vendor/jquery-validation/dist/*.min.js"></script>
    <script asp-src-include="~/vendor/jquery-validation-unobtrusive/*.min.js"></script>
    <script asp-src-include="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script asp-src-include="~/js/my-blog.min.js"></script>
    <script async asp-src-include="~/admin/ckeditor/ckeditor.js"></script>
  
    @RenderSection("Script", false)
</body>
</html>
<style>
    .container img {
        max-width: 100%;
        height: auto;
    }

    .btn-link:hover, .btn-link:focus {
        color: #2DA4E1;
        text-decoration: none;
    }

    .btn-link {
        color: #16181b;
    }

    .dropdown:hover > .dropdown-menu {
        display: block;
    }

    .dropdown > .dropdown-menu !important {
        display: none;
    }
</style>