MySite/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using MySite.Models;
namespace MySite.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IPost repository;

        public NavigationMenuViewComponent(IPost repository)
        {
            this.repository = repository;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View
                (
                repository.Posts
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x)
                );
        }

    }
}

MySite/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MySite.Models;
using MySite.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace MySite.Controllers
{
    public class HomeController : Controller
    {
        private readonly UserManager<User> _userManager;
        private IPost _postRepository;
        private IFolower _folower;
        private IProfile _profile;
        public int PageSize = 4;

        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);


        public HomeController(IPost postRepository, IFolower folower, UserManager<User> userManager, IProfile profile)
        {
            _postRepository = postRepository;
            _folower = folower;
            _userManager = userManager;
            _profile = profile;
        }
        public IEnumerable<Post> SortPosts(IEnumerable<Post> posts, string selectedSort)
        {
            switch (selectedSort)
            {
                case "New":
                    posts = _postRepository.Posts.OrderByDescending(l => l.DateTime);
                    break;
                case "Old":
                    posts = _postRepository.Posts.OrderBy(l => l.DateTime);
                    break;
                default:
                    posts = _postRepository.Posts.OrderByDescending(l => l.PostID);
                    break;
            }
            return posts;
        }
        public IActionResult Index(string category, string sortSelected, int page = 1, string title = null, int requestAjax = 0)
        {

            var posts = SortPosts(_postRepository.Posts, sortSelected);//Default give order?postID

            int totalItems = 1;
            if (title != null)
            {
                totalItems = _postRepository.Posts
                        .Where(p => p.Allow == 1)
                        .Where(p => category == null || category.Equals("All") || p.Category.Equals(category))
                        .Where(p => title == null ||
                        p.Title.ToLower().Replace(" ", string.Empty)
                        .Contains(title.ToLower().Replace(" ", string.Empty)))
                        .OrderBy(p => p.PostID).Count();
            }///check page 
            else if (category == null || category.Equals("All"))
            {
                totalItems = _postRepository.Posts.Where(p => p.Allow == 1).Count();
            }
            else
            {
                totalItems = _postRepository.Posts.Where(p => p.Allow == 1)
                         .Where(e => e.Category == category).Count();
            }
            var model = new PostViewModel
            {
                Posts = posts
                        .Where(p => p.Allow == 1)
                        .Where(p => category == null || category.Equals("All") || p.Category.Equals(category))
                        .Where(p => title == null ||
                        p.Title.ToLower().Replace(" ", string.Empty)
                        .Contains(title.ToLower()
                        .Replace(" ", string.Empty)))
                        .Skip((page - 1) * PageSize)
                        .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = totalItems
                },

                Categories = _postRepository.Posts.Where(p => p.Allow == 1)
                        .Select(x => x.Category)
                        .Distinct().OrderBy(x => x),
                CurrentCategory = category,
                CurrentSearchTitle = title

            };
            if (requestAjax == 1)
            {
                return PartialView("ShowBlocksPartial", model);
            }
            return View(model);

        }



        public async Task<IActionResult> Post(int postID, string returnUrl)
        {
            var Post = _postRepository?.Posts?.FirstOrDefault(p => p.PostID == postID);
            var PostUser = _userManager?.Users?.FirstOrDefault(p => p.Id.Equals(Post.UserID));
            var currentUser = await GetCurrentUserAsync();
            var userId = currentUser?.Id;
            var FolowerProfile = _profile?.Profiles?.FirstOrDefault(p => p?.UserID == PostUser?.Id);
            var ProfileFolowers = _folower?.Folowers?.Where(i => i.FolowerID.Equals(FolowerProfile?.UserID));
            bool _isSubscribe = false;
            if (currentUser != null)
            {
                if (FolowerProfile != null && userId.Equals(FolowerProfile.UserID))
                {
                    _isSubscribe = true;
                }
                else if (ProfileFolowers != null)
                {
                    foreach (var item in ProfileFolowers)
                    {
                        if (item.UserID.Equals(userId))
                        {
                            _isSubscribe = true;
                            break;
                        }
                    }
                }
            }

            if (Post != null && PostUser != null)
            {
                return View(new PostContentViewModel()
                {
                    Post = Post,
                    ReturnUrl = Url.IsLocalUrl(returnUrl) ? returnUrl : "/",
                    PostFavorites = _folower.Folowers.Count(p => p.FolowerID.Equals(PostUser.Id)),
                    isSubscribe = _isSubscribe
                });
            }
            else
            {
                return BadRequest();
            }
        }
        public FileContentResult GetAvatar(int profileID)
        {
            Profile profile = _profile.Profiles.FirstOrDefault(p => p.ProfileID == profileID);
            if (profile != null && profile.ImageData != null && profile.ImageMimeType != null)
            {
                return File(profile.ImageData, profile.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
        public FileContentResult GetImage(int postID)
        {
            Post product = _postRepository.Posts.FirstOrDefault(p => p.PostID == postID);
            if (product != null && product.ImageData != null && product.ImageMimeType != null)
            {
                return File(product.ImageData, product.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
        [Authorize]
        public IActionResult AddPost()
        {
            return View(new Post());
        }

        public IActionResult About() => View();
        public IActionResult Contact() => View();
        public IActionResult Test() => View();


    }
}

MySite/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MySite.Models;
using MySite.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;


namespace MySite.Controllers
{
    public class ProfileController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IProfile _profile;
        private readonly IPost _post;
        private readonly IFolower _folower;
        public const int ImageMinimumBytes = 512;
        public int PageSize = 4;
        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public ProfileController(UserManager<User> userManager, IProfile profile, IPost post, IFolower folower)
        {
            _userManager = userManager;
            _profile = profile;
            _post = post;
            _folower = folower;
        }
        private PostViewModel SetPost(IEnumerable<Post> posts, string category, int page = 1, string title = null)
        {
            PostViewModel model = new PostViewModel()
            {
                Posts = posts
                    .Where(p => category == null || category.Equals("All") || p.Category == category)
                    .Where(p => title == null ||
                     p.Title.ToLower().Replace(" ", string.Empty)
                    .Contains(title.ToLower()
                    .Replace(" ", string.Empty)))
                    .OrderBy(p => p.PostID)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null || category == "All" ?
                        posts.Count() :
                        posts.Where(e =>
                            e.Category == category).Count()
                },
                CurrentCategory = category,
                Categories = posts.Select(x => x.Category).
                       Distinct().OrderBy(x => x)
            };
            if (model.Posts.Count(p => p.PostID == p.PostID) == 0)
            {
                model = null;
            }
            return model;
        }

        public async Task<IActionResult> Index(int profileID, string category, int page = 1, string title = null, int ajaxRequest = 0, int allowEdit = 0)
        {
            var user = await GetCurrentUserAsync();
            bool isSubscribe = false;
            Profile profile = _profile.Profiles.FirstOrDefault(p => p.ProfileID == profileID);
            if (profile != null)
            {

                var posts = _post.Posts.Where(p => p.ProfileID == profile.ProfileID);
                PostViewModel postModel = SetPost(posts, category, page, title);
                var userPostAccount = _userManager.Users.FirstOrDefault(p => p.Id == profile.UserID);//Who create post
                bool _Me = true ? user != null && user.Id == userPostAccount.Id : false;
                //Check isSubscribe
                if (_Me || _folower.Folowers.FirstOrDefault(u => u.UserID == user.Id && u.FolowerID == userPostAccount.Id) != null)
                    isSubscribe = true;
                //
                List<FolowerListViewModel> folowingList = null;
                List<FolowerListViewModel> folowersList = null;
                if (_Me)
                {
                    //Create Folowing List
                    folowingList = new List<FolowerListViewModel>();

                    foreach (var item in _folower.Folowers.Where(u => u.UserID == user.Id))
                    {
                        var currentFolowerAccount = _userManager.Users.FirstOrDefault(u => u.Id == item.FolowerID);
                        var currentFolowerProfile = _profile.Profiles.FirstOrDefault(p => p.UserID == item.FolowerID);
                        folowingList.Add(
                            new FolowerListViewModel
                            {
                                FolowerID = item.FolowerID,
                                UserID = user.Id,
                                ImageData = currentFolowerProfile.ImageData,
                                ImageMimeType = currentFolowerProfile.ImageMimeType,
                                UserName = currentFolowerAccount.UserName,
                                isSubscribe = isSubscribe
                            });
                    }
                    //Create Folowers List
                    folowersList = new List<FolowerListViewModel>();

                    foreach (var item in _folower.Folowers.Where(u => u.FolowerID == user.Id))
                    {
                        var currentFolowerAccount = _userManager.Users.FirstOrDefault(u => u.Id == item.UserID);
                        var currentFolowerProfile = _profile.Profiles.FirstOrDefault(p => p.UserID == item.UserID);
                        folowersList.Add(
                            new FolowerListViewModel
                            {
                                FolowerID = item.FolowerID,
                                UserID = user.Id,
                                ImageData = currentFolowerProfile.ImageData,
                                ImageMimeType = currentFolowerProfile.ImageMimeType,
                                UserName = currentFolowerAccount.UserName,
                                isSubscribe = isSubscribe
                            });
                    }
                }
                //
                ProfileViewModel profileModel = new ProfileViewModel
                {
                    Profile = profile,
                    email = userPostAccount.Email,
                    MyPosts = postModel,
                    Me = _Me,//if user exist and userId == profileID
                    AllowEdit = _Me ? allowEdit : 0,
                    isSubscribe = isSubscribe,
                    folowersList = folowersList,
                    folowingList = folowingList
                };
                if (ajaxRequest == 1)//FOR AJAX REQUEST
                {
                    return PartialView("ShowProfilePageHeader", profileModel);
                }
                return View(profileModel);

            }
            return NotFound();
        }
        public IActionResult AjaxSearch(int profileID, string category, string title = null, int page = 1)
        {
            var profile = _profile.Profiles.FirstOrDefault(p => p.ProfileID == profileID);
            if (profile != null)
            {
                var posts = _post.Posts.Where(p => p.ProfileID == profile.ProfileID);
                PostViewModel postModel = SetPost(posts, category, page, title);
                return PartialView("ShowBlocksPartial", postModel);
            }
            return PartialView("ShowBlockPartial", null);

        }

        //[HttpGet]
        //public IActionResult Edit()
        //{

        //    return RedirectToAction("Index", new { ajaxRequest = 0, allowEdit = 1,profileID= });
        //}
        [HttpPost]
        public async Task<IActionResult> Edit(Profile model, IFormFile Image = null)
        {

            var CurrentUser = await GetCurrentUserAsync();

            if (CurrentUser != null && ModelState.IsValid)
            {

                var profile = _profile.Profiles.FirstOrDefault(p => p.UserID == CurrentUser.Id);

                if (Image != null)
                {

                    if (IsImage(Image))
                    {
                        profile.ImageMimeType = Image.ContentType;
                        profile.ImageData = new byte[Image.Length];
                        Image.OpenReadStream().Read(profile.ImageData, 0, (int)Image.Length);


                    }
                    else
                    {
                        TempData["error"] = $"It's not image";
                    }

                }
                profile.FirstName = model.FirstName;
                profile.LastName = model.LastName;
                profile.Description = model.Description;
                model.ProfileID = profile.ProfileID;



                _profile.SaveProfile(profile);

                ProfileViewModel profileModel = new ProfileViewModel()
                {
                    Profile = model,
                    email = CurrentUser.Email
                };
                return RedirectToAction("Index", new { profileID = profile.ProfileID });
            }
            else if (CurrentUser == null)
            {
                return NotFound();
            }
            else
            {
                ProfileViewModel profileModel = new ProfileViewModel()
                {
                    Profile = model,
                    email = CurrentUser.Email
                };
                return RedirectToAction("Index", new { profileID = profileModel.Profile.ProfileID });
            }
        }
        [HttpPost]
        public async Task<JsonResult> SubAjax([FromBody]AjaxPostViewModel model)
        {
            var CurrentUser = await GetCurrentUserAsync();
            Post FolowerAccount = null;
            Profile FolowerProfile = null;
            Profile CurrentUserProfile = null;

            if (model.postID == 0)//TODO VIEW THIS ?
            {
                FolowerProfile = _profile.Profiles.FirstOrDefault(p => model.profileID == p.ProfileID);
            }
            else
            {
                FolowerAccount = _post.Posts.FirstOrDefault(p => p.PostID == model.postID);
                if (FolowerAccount != null)
                    FolowerProfile = _profile.Profiles.FirstOrDefault(p => FolowerAccount.UserID == p.UserID);
            }

            if (CurrentUser != null && FolowerProfile != null)
            {

MySite/Views/Home/About.cshtml
<!-- Page Header -->
<header class="masthead" style="background-image: url('@Url.Content("~/img/about-bg.jpg")')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="page-heading">
                    <h1>About Me</h1>
                    <span class="subheading">This is what I do.</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
        </div>
    </div>
</div>
<hr>

MySite/Views/Home/AddPost.cshtml
@model Post
<header class="masthead" style="background-image: url('@Url.Content("~/img/AddPost.jpg")')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Create your post</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content -->
<div class="container">
    @Html.Partial("ShowEditFormForPost", Model)
</div>
<script>
    CKEDITOR.replace("Description");
    CKEDITOR.replace("Text");
</script>

MySite/Views/Home/Index.cshtml
@model PostViewModel
<!-- Page Header -->
<header class="masthead" style="background-image: url('@Url.Content("~/img/home-bg.jpg")')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Marc Blog</h1>
                    <span class="subheading">Օnly fresh news</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content -->
<div class="container">
    @{
        BreadcrumbViewModel broad = new BreadcrumbViewModel()
        {
            Active = true,
            Category = Model.CurrentCategory
        };
    }

    @Html.Partial("ShowBreadcrumb", broad)
    @if (TempData["message"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert" style="color:cornflowerblue;background-color:#F2F2F3;border-color:#F2F2F3;font-size:14px">
            @TempData["message"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }




    @using (Html.BeginForm("Index", "Home", FormMethod.Get, new { id = "myFormSearch" }))
    {

        <div class="d-flex flex-row bd-highlight mb-3">
            <div class="p-2 bd-highlight" style="width:160px">
                @*@await Component.InvokeAsync("NavigationMenu")*@
                <select class="custom-select" id="CategorySelected"
                        aria-label="Example select with button addon"
                        style="font-size:15px" name="category">
                    <option value="All" selected>All</option>
                    @foreach (string category in Model.Categories)
                    {
                        if (category.Equals(Model.CurrentCategory))
                        {
                            <option value="@category" selected>@category</option>
                        }
                        else
                        {
                            <option value="@category">@category</option>
                        }

                    }
                </select>
            </div>
            <div class="main p-2 bd-highlight">
                <!-- Actual search box -->
                <div class="form-group has-search">
                    <span class="fa fa-search form-control-feedback"></span>
                    <input type="text" class="form-control" placeholder="Search" name="title" id="search">
                </div>
            </div>
            <div class="p-2 bd-highlight">
                <button type="submit" class="btn btn-primary" style="padding:8px;border-radius:8px">
                    <p style="font-size:12px;display:inline">Search</p>
                </button>
            </div>

        </div>
    }



    <div class="d-flex flex-row-reverse bd-highlight" style="height:23px">
        <div class="p-1 bd-highlight">
            <form action="/" method="get" id="sortForm">
                <select class="custom-select" id="sortSelected"
                        aria-label=""
                        style="font-size:small;height:32px;width:70px" name="category">
                    <option value="New">New</option>
                    <option value="Old">Old</option>
                </select>
            </form>
        </div>
    </div>
    <hr />
    <div class="float-right" style="margin-bottom:1px">

        <a asp-action="AddPost" asp-controller="Home" title="Add Post" style="color:#0085A1" id="AddPost">
            <i class="fas fa-plus-circle"></i>
        </a>

    </div>
    <div id="postContent">
        @Html.Partial("ShowBlocksPartial", Model)
    </div>
</div>

@section Script{
    <script>

        $("#myFormSearch").submit(function (e) {
            console.log("It's Here");
            var search = $("#search").val();
            var category = $("#CategorySelected").val();
            e.preventDefault();
            console.log("Serch " + search + " Category " + category);

            $("#postContent").load("/Index", { title: search, category: category, requestAjax: 1 });
        });
        $("#sortSelected").change(function (e) {
            e.preventDefault();

            var sortSelected = $("#sortSelected").val();

            $("#postContent").load("/Index", { sortSelected: sortSelected, requestAjax: 1, category: "" });
        });

    </script>
}


@section Style{
    <style>

        /* Styles for wrapping the search box */

        .main {
            width: 100%;
        }

        /* Bootstrap 4 text input with search icon */

        .has-search .form-control {
            padding-left: 2.375rem;
        }

        .has-search .form-control-feedback {
            position: absolute;
            z-index: 2;
            display: block;
            width: 2.375rem;
            height: 2.375rem;
            line-height: 2.375rem;
            text-align: center;
            pointer-events: none;
            color: #aaa;
        }

        #AddPost:hover {
            color: #00657b !important;
        }
    </style>
}

MySite/Views/Home/Post.cshtml
@model PostContentViewModel
<!-- Page Header -->
<header class="masthead" style="background-image: url('@Url.Action("GetImage", "Home",
               new {Model.Post.PostID })')">


    <div class="overlay"></div>
    <div class="container">
        <div class="row" style="display:inline">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-heading ">
                    <h1>@Model.Post.Title</h1>
                    <h2 class="subheading" name="description">@Html.Raw(Model.Post.Description)</h2>
                    <span class="meta">
                        Posted by
                        <a href="#">@Model.Post.Author</a>
                        on @Model.Post.DateTime.ToShortDateString()
                    </span>
                </div>
                <span class="fa-pull-right">
                    <form asp-action="SubAjax" asp-controller="Profile" id="myForm">
                        <input type="hidden" name="postID" id="postID" value="@Model.Post.PostID" />
                        <input type="hidden" name="returnUrl" id="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                        <button class="btn  btn-primary btn-sm" style="width:125px;height:20px" id="subscribe" type="submit">
                            @if (Model.isSubscribe)
                            {<p style="margin-top:-10px;margin-left:-16px;color:#C0C0C0" id="mySubText">Subscribed:@Model.PostFavorites</p>}
                            @if (!Model.isSubscribe)
                            {<p style="margin-top:-10px;margin-left:-16px" id="mySubText">Subscribe:@Model.PostFavorites</p>}
                        </button>
                    </form>

                </span>

            </div>

        </div>
    </div>
</header>
@{
    BreadcrumbViewModel broad = new BreadcrumbViewModel()
    {
        Active = false,
        Category = Model.Post.Category,
        CurrentName = Model.Post.Title

    };
}
@Html.Partial("ShowBreadcrumb", broad)
<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            @Html.Raw(Model.Post.Text)
        </div>
    </div>
</article>
<hr>
<div id="disqus_thread"></div>
<script>

    (function () { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://marcblog-1.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the comment</noscript>

<script type="text/javascript">
    var countFolower = Number(@Model.PostFavorites);
    $("#myForm").submit(function (event) {
        console.log("Working");
        event.preventDefault();
        var testData =
        {
            'postID': $("#postID").val(),
            'TestStr2': $("#returnUrl").val()
        };

        $.ajax({
            type: "POST",
            url: '@Url.Action("SubAjax","Profile")',
            data: JSON.stringify(testData),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: successFunc,
            error: errorFunc
        });
    });
    function successFunc(data, status) {
        var sub = document.getElementById("mySubText");
        if (data === "Add") {

            sub.innerHTML = "Subscribed:" + (countFolower += 1);
            sub.style.color = "#C0C0C0";


        } else if (data === "Delete") {

            sub.innerHTML = "Subscribe :" + (countFolower -= 1);
            sub.style.color = "#FFFFFF";
        } else if (data === "NewUser") {
            alert("Please Register or Login");
        }
    }

    function errorFunc(errorData) {
        alert('Ошибка' + errorData.responseText);
    }
</script>

MySite/Views/Home/Test.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Example Title</title>
</head>
<body>

</body>
</html>